server:
  port: 8080


# mybatis

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.xzw.oauth.entity
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauthdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&autoReconnect=true
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  main:
    allow-bean-definition-overriding: true